# Generated by Django 5.0.2 on 2024-02-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event/')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('pre_requisites', models.TextField(blank=True)),
                ('location', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
                ('duration', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event/')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
                ('duration', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
