# Generated by Django 5.0.2 on 2024-02-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('student_id', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=64)),
                ('degree', models.CharField(choices=[('Hazırlık', 'Hazırlık'), ('1. Sınıf', '1. Sınıf'), ('2. Sınıf', '2. Sınıf'), ('3. Sınıf', '3. Sınıf'), ('4. Sınıf', '4. Sınıf'), ('5. Sınıf', '5. Sınıf'), ('6. Sınıf', '6. Sınıf'), ('Yüksek Lisans', 'Yüksek Lisans'), ('Doktora', 'Doktora'), ('Mezun', 'Mezun')], max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('group_chat_platform', models.CharField(choices=[('Signal', 'Signal'), ('Telegram', 'Telegram'), ('WhatsApp', 'WhatsApp')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
