# Generated by Django 5.0.2 on 2024-02-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_boardmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='role',
            field=models.CharField(choices=[('Başkan', 'Başkan'), ('Başkan Yardımcısı', 'Başkan Yardımcısı'), ('Genel Sekreter', 'Genel Sekreter'), ('Eğitim ve Arge Sorumlusu', 'Eğitim ve Arge Sorumlusu'), ('Kurumsal İlişkiler Sorumlusu', 'Kurumsal İlişkiler Sorumlusu'), ('Mali İşler Sorumlusu', 'Mali İşler Sorumlusu'), ('Halkla İlişkiler Sorumlusu', 'Halkla İlişkiler Sorumlusu'), ('Organizasyon Sorumlusu', 'Organizasyon Sorumlusu')], max_length=32),
        ),
    ]
