# Generated by Django 5.0.8 on 2024-08-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_boardmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_in_group_chat',
            field=models.BooleanField(default=False),
        ),
    ]
